### ISSUE TITLE
Deactivating client causes a panic

### ISSUE THREAD

**Issue by skyflyer** [RustAudio/rust-jack#160]
OS: macOS 12.1 (M1 and Intel)  
JACK version: jackdmp 1.9.19  

When deactivating client, the assertion in the `client_impl.rs:620` fails.

```rs
/// Close the client.
impl Drop for Client {
    fn drop(&mut self) {
        let _m = CREATE_OR_DESTROY_CLIENT_MUTEX.lock().unwrap();

        debug_assert!(!self.raw().is_null()); // Rep invariant
                                              // Close the client
        sleep_on_test();
        let res = unsafe { j::jack_client_close(self.raw()) }; // close the client
        sleep_on_test();
        assert_eq!(res, 0); // <--- here
        self.0 = ptr::null_mut();
    }
}
```

Steps to reproduce:

1. Run jack: `jackd -ddummy -r48000 -p1024`
2. Run playback_capture example with `cargo run` or directly with `./target/debug/playback_capture`
3. Observe the panic:
```
JACK: shutdown with status FAILURE | SERVER_ERROR because "JACK server has been closed"
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-1`,
 right: `0`', /.../rust-jack/src/client/client_impl.rs:620:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Not sure if it is related, but... when running tests with `dummy` backend, one of the tests fails:

```
test client::test::client_uuid ... thread panicked while panicking. aborting.
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/.../rust-jack/target/debug/deps/jack-bcb9f8cfeb1a10d0` (signal: 5, SIGTRAP: trace/breakpoint trap)
```

Let me know if I can help in any way (though my rust skills are limited :().

**Comment by wmedrano** [comment]
I'm not sure I can do anything about the underlying issue of `jack_client_close` returning an error. However, the panic can be downgraded to an `error!` statement.

**Comment by skyflyer** [comment]
I'm not sure what `error!` does? Is this a macro I'm not aware of?

I understand it is difficult to do anything useful, especially in `drop`, but panicking doesn't sit well :)

I'll try and repro this code on the same machine with C/C++ - I'm not sure whether it is jack related or rust-jack related. I suppose you're not seeing this error on your platform?

**Comment by skyflyer** [comment]
@wmedrano, I don't know much about Rust, so I'm just thinking, would it make sense to replace `assert_*` with `debug_assert_*` in order to strip them out of the release builds?

I'm just brainstorming: rust-jack is a wrapper around JACK library; the library itself does not panic, but reports errors in a "classic" C fashion by providing result codes for the operations. This rust wrapper upgrades that and makes it rust-friendly by providing `Result` objects. 

The issue at hand is problematic because it happens in `drop`. Now I'm not sure why this is, because my code actually calls `client.deactivate`. I'm providing full backtrace below, but I'm thinking this is actually a race condition happening because from the backtrace it seems that the error is actually happening in ClosureProcessHandler.

I "accidentally" had one successful run, which led me to believe it might be a race condition in the callback.

<details>
<summary>Backtrace details</summary>

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-1`,
 right: `0`', /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/jack-0.8.4/src/client/client_impl.rs:620:9
stack backtrace:
   0:        0x109a44f91 - std::backtrace_rs::backtrace::libunwind::trace::h47a7835575e4d9f3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x109a44f91 - std::backtrace_rs::backtrace::trace_unsynchronized::he8690599afcb5399
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x109a44f91 - std::sys_common::backtrace::_print_fmt::h0617b83dce07f61f
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x109a44f91 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c059b532d34bdd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x109a5b05b - core::fmt::write::hefb311138778afb5
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:        0x109a421ea - std::io::Write::write_fmt::h0e0ed87b18ae870c
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:        0x109a46775 - std::sys_common::backtrace::_print::hcb332ccba1b9e587
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x109a46775 - std::sys_common::backtrace::print::h8f35339db66741dd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x109a46775 - std::panicking::default_hook::{{closure}}::h43f0e51e5825bd5b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:        0x109a4635f - std::panicking::default_hook::ha1c3473cbcf391f7
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:        0x109a46e60 - std::panicking::rust_panic_with_hook::h0db3c4ba5fb4dc12
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:        0x109a468fe - std::panicking::begin_panic_handler::{{closure}}::hc6d8c92efeef5a19
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  12:        0x109a45407 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ffb59e898e02a83
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x109a4686a - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:        0x109a64a4f - core::panicking::panic_fmt::h7d73f67464d78916
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:        0x109a5a1f7 - core::panicking::assert_failed_inner::h552528527490242b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:188:17
  16:        0x109a5ede4 - core::panicking::assert_failed::h7dc02e2500789424
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:145:5
  17:        0x10989c953 - <jack::client::client_impl::Client as core::ops::drop::Drop>::drop::h53d5a42e42950317
                               at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/jack-0.8.4/src/client/client_impl.rs:620:9
  18:        0x109887265 - core::ptr::drop_in_place<jack::client::client_impl::Client>::h782a0024fe774867
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
  19:        0x109886cc5 - core::ptr::drop_in_place<(jack::client::client_impl::Client,(),jack::client::handler_impls::ClosureProcessHandler<jack_recorder::recorder::record::{{closure}}>)>::h8013aed4ebae6bff
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
  20:        0x109886f43 - core::ptr::drop_in_place<core::result::Result<(jack::client::client_impl::Client,(),jack::client::handler_impls::ClosureProcessHandler<jack_recorder::recorder::record::{{closure}}>),jack::jack_enums::Error>>::h37ada34e151a4edd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ptr/mod.rs:188:1
  21:        0x109883d20 - jack_recorder::recorder::record::ha6d0d1c3a3206638
                               at /Volumes/Drugi/Users/user/jack_recorder/src/recorder.rs:103:5
  22:        0x109885c6f - jack_recorder::main::h8e539bbed47057b1
                               at /Volumes/Drugi/Users/user/jack_recorder/src/main.rs:31:13
  23:        0x1098868ae - core::ops::function::FnOnce::call_once::h79122c4457e4533f
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  24:        0x1098820e1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7a8e5140ebf91248
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
  25:        0x10987fc14 - std::rt::lang_start::{{closure}}::h85b5e3638dfbb75e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145:18
  26:        0x109a44c3f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h366f85254a0aedbd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  27:        0x109a44c3f - std::panicking::try::do_call::hcd7d6ba18808215d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  28:        0x109a44c3f - std::panicking::try::h8b7328b76a891d08
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  29:        0x109a44c3f - std::panic::catch_unwind::h63bbd5ef51caa433
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  30:        0x109a44c3f - std::rt::lang_start_internal::{{closure}}::h2efd4ac38212ab36
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  31:        0x109a44c3f - std::panicking::try::do_call::hfdf1ca9f7283bb6b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  32:        0x109a44c3f - std::panicking::try::h5e8a1aa20c127c08
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  33:        0x109a44c3f - std::panic::catch_unwind::he9efa865311db8e6
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  34:        0x109a44c3f - std::rt::lang_start_internal::hb74872162e3d56c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  35:        0x10987fbee - std::rt::lang_start::had2159f89a30228f
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:144:17
  36:        0x109886796 - <unknown>
                               at /Volumes/Drugi/Users/user/jack_recorder/src/main.rs:13:19
```

</details>

**Comment by wmedrano** [comment]
Sorry its been a while. Is this still an issue? I think downgrading panic to `error!` on drop is reasonable.

**Comment by skyflyer** [comment]
Hi! Yep, still an issue; I'm actually experiencing segfaults when disconnecting the client within a master process - something I haven't observed before when it was a simple CLI tool. No issues on linux though, and there are some open issues about that in JACK's repository.

**Comment by skyflyer** [comment]
Hello! The latest jack build does not exhibit errors anymore. It seems that the issue has been fixed there so no need to modify any code (anymore). :)

Here's the issue relating to OS X error which was closed, for posterity: https://github.com/jackaudio/jack2/issues/841

Thanks!

/close
